### PR TITLE
Etsi populate

### PR DESCRIPTION
**Pull request by dmytro-kyrychenko**

### CODE REVIEW

**Comment by richardzilincikPantheon** [comment]
@dmytro-kyrychenko is this PR ready for review? If so please mark it as such.

**Comment by richardzilincikPantheon** [comment]
I realized that after my changes in #743, populating modules from the additional repos could simply be done with adding the URLs to the repos [here](https://github.com/YangCatalog/module-compilation/blob/develop/cronjobs/run_download_github.sh#L16) and adding the corresponding directories [here](https://github.com/YangCatalog/backend/pull/743/files#diff-b487770d3608748bfc025a94911785bbd26984cf1f69c55a480904df2b42faa3R126).

**Comment by dmytro-kyrychenko** [comment]
@richardzilincikPantheon @SlavomirMazurPantheon so, should I remove this changes and add those urls to the repo?

**Comment by richardzilincikPantheon** [comment]
I think so, yeah.

**Comment by SlavomirMazurPantheon** [comment]
Someone should test whether it will be working correctly when we add `'standard/etsi'` [here](https://github.com/YangCatalog/backend/pull/743/files#diff-b487770d3608748bfc025a94911785bbd26984cf1f69c55a480904df2b42faa3R126)
If yes, then we do not need to have separate script, which will triggers this populate.

**Comment by richardzilincikPantheon** [comment]
Superseded by #743

**Pull request closed without merging**
