### PR TITLE
refactored code and added In Progress job_log for scripts

### PR DESCRIPTION
**Pull request by Fagtoy**
tried to minimize intends
replaced empty dictionaries creating, and then assigning key-value pairs to them with creating dictionaries with already filled key/values
replaced .format() with f-strings
added job_log() function with "In Progress" status to scripts that use job_log() function with "Failure"/"Success" statuses

### CODE REVIEW

**Comment by SlavomirMazurPantheon** [comment]
Refactoring parts looks good, I like these changes.

**Comment by SlavomirMazurPantheon** [comment]
What about using `Enum` for the status of the job?

**Comment by Fagtoy** [comment]
> What about using `Enum` for the status of the job?

Yeah, it would be great, I'll do it

**Comment by Fagtoy** [comment]
> What about using `Enum` for the status of the job?

done

**Review by SlavomirMazurPantheon — APPROVED** [review]

**Pull request merged**
