### PR TITLE
chore: resolver abstractclass created

### PR DESCRIPTION
**Pull request by SlavomirMazurPantheon**
- resolver abstractclass created
- basic resolver created
- first batch of resolvers created: revision, organization, namespace

Signed-off-by: Slavomir Mazur <slavomir.mazur@pantheon.tech>

### CODE REVIEW

**Review by richardzilincikPantheon — CHANGES_REQUESTED** [review]
The unused methods for resolving the namespace, organization, etc. should be removed now.

**Comment by SlavomirMazurPantheon** [comment]
So maybe `chore:` would be better?

**Comment by richardzilincikPantheon** [comment]
Yes I think `chore:` is a better fit.

**Comment by SlavomirMazurPantheon** [comment]
PR name updated and unused methods removed from modules.py script

**Comment by SlavomirMazurPantheon** [comment]
Sorry, I must have missed it the first time

**Review by richardzilincikPantheon — APPROVED** [review]

**Pull request merged**
